# Generated by Django 2.0.7 on 2018-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
